### ISSUE TITLE
exec  : echo kl > o === > lecho se fait et pas la redirection. linverse doit etre vrai 

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell.c#67]
si : echo kl > o

===> on devrait avoir la creation dun fichier o avec kl dedans 
```
faboussa@z1r11p5:~/minishell$ echo kl> o
faboussa@z1r11p5:~/minishell$ cat o
kl
```
nous on a lecho qui se met en route, puis pas de creation de fichier o: 
```
>>>  Minishell>$ echo kl> o
kl > o
```

**Comment by melobern** [comment]
Voir ici : https://github.com/faboussard/42_minishell.c/issues/66
